version: 2.1

jobs:
  insights:
    docker:
      - image: cimg/base:stable
    resource_class: small
    steps:
      - run:
          name: ingest Insights API
          command: |
            curl -s -H "circle-token: $CIRCLE_TOKEN" https://circleci.com/api/v2/insights/gh/circleci/orb-service/workflows?reporting-window=last-30-days >> insightdata.json
            INSIGHT_DATA2=$(jq -c '.items' insightdata.json)
            echo $INSIGHT_DATA2
            echo "export INSIGHT_DATA_SLACK='${INSIGHT_DATA2}'" >> $BASH_ENV
      - run:
          name: check
          command: |
            printenv INSIGHT_DATA_SLACK | jq .
            
workflows:
  main:
    jobs:
      - insights
